# Generated by Django 6.1.1 on 2026-10-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_observatory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertrule',
            name='metric',
            field=models.CharField(choices=[('error_rate', 'HTTP 5xx rate (%)'), ('p95_latency', 'Request P95 latency (ms)'), ('p99_latency', 'Request P99 latency (ms)'), ('request_rate', 'Requests per minute'), ('exception_count', 'Exceptions in window'), ('issue_occurrences', 'Occurrences of the busiest issue in window'), ('external_failure_rate', 'External API failure rate (%)'), ('external_p95', 'External API P95 latency (ms)'), ('slow_query_count', 'Slow queries in window'), ('db_max_ms', 'Slowest database query (ms)'), ('login_failures', 'Failed logins in window'), ('cpu_percent', 'Server CPU usage, average (%)'), ('memory_percent', 'Server memory usage, average (%)'), ('disk_percent', 'Fullest disk volume (%)'), ('custom', 'Custom metric (sum in window)')], max_length=40),
        ),
    ]
